config/routes.rb
Rails.application.routes.draw do
  root to: "codes#index"
  
  resources :codes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/code.rb
class Code < ApplicationRecord
  validates :rating, numericality: { only_integer: true }
  validates_presence_of :problem_description
  validates_presence_of :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private 
  def error_message(errors)
    errors.full_messages.join(',')
  end
end

app/controllers/codes_controller.rb
class CodesController < ApplicationController
  def index
    @codes = Code.all
  end

  def new
    @code = Code.new
  end

  def create
    code = Code.new(code_params)
    if code.save
      redirect_to codes_path 
    else 
      redirect_to new_code_path
      flash[:alert] = "Error: #{error_message(code.errors)}"
    end
  end

  def show
    @code = Code.find(params[:id])
  end

  private
  def code_params
    params.require(:code).permit(:title, :rating, :problem_description, :solution)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/codes_helper.rb
module CodesHelper
end

app/views/codes/index.html.erb
<h1>Bryce's List of Completed Code Challenges</h1>
<ol>
<% @codes.each do |code| %>
    <li><%= link_to "#{code.title}", code_path(code.id) %></li>
<% end %>
</ol>

app/views/codes/new.html.erb
<h1>New Code Challenge</h1>

<%= form_with model: @code, local: true do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :rating %>
  <%= f.text_field :rating %>
  <br>
  <%= f.label :problem_description %>
  <%= f.text_field :problem_description %>
  <br>
  <%= f.label :solution %>
  <%= f.text_field :solution %>
  <br>
  <%= f.submit %>
<% end %>

app/views/codes/show.html.erb
<h1><%= @code.title %></h1>
<ul>
  <li>Code Difficulty (1 = Hardest, 10 = Easiest): <%= @code.rating %></li>
  <li>The Challenge: <%= @code.problem_description %></li>
  <% unless @code.solution == nil %>
    <li>This Code Challenge's Solution: <%= @code.solution %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Code Challenges</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div>
        <%= msg %>
      </div>
    <% end %>
    <section>
      <%= link_to "Home", root_path %>
      &nbsp;
      <%= link_to "Add Code Challenge To Directory", new_code_path %>
    </section>
    <%= yield %>
  </body>
</html>